# generated by ChatGPT to connect to the DSLD API, 
# search for pre-workout products, and store results in a MySQL database.

import time
import requests
import mysql.connector
from mysql.connector import errorcode
import json

BASE = "https://api.ods.od.nih.gov/dsld/v9"
HEADERS = {"Accept": "application/json"}

SEARCH_TERMS = [
    '"pre workout"', '"pre-workout"', 'preworkout', '"pump"'
]

def get_db():
    return mysql.connector.connect(
        host="localhost",
        user="root",
        password="password",
        database="mydb",
    )

def ensure_tables(conn):
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        dsld_label_id INT NOT NULL UNIQUE,
        full_name VARCHAR(512),
        brand_name VARCHAR(256),
        upc_sku VARCHAR(64),
        entry_date DATE,
        off_market TINYINT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS products_raw (
        dsld_label_id INT NOT NULL UNIQUE,
        raw_json JSON NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS ingredients (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(512) NOT NULL UNIQUE
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS product_ingredients (
        product_id INT NOT NULL,
        ingredient_id INT NOT NULL,
        amount DECIMAL(12,4) NULL,
        unit VARCHAR(32) NULL,
        raw_text VARCHAR(1024) NULL,
        PRIMARY KEY (product_id, ingredient_id),
        FOREIGN KEY (product_id) REFERENCES products(id),
        FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
    )
    """)
    conn.commit()
    cur.close()

def dsld_search(q, status=2, size=200, start=0):
    # /v9/search-filter supports q plus pagination via from/size (per docs) :contentReference[oaicite:2]{index=2}
    params = {
        "q": q,
        "status": status,  # 2=all, 1=on market, 0=off market :contentReference[oaicite:3]{index=3}
        "from": start,
        "size": size,
        "sort_by": "_score",
        "sort_order": "desc",
    }
    r = requests.get(f"{BASE}/search-filter", params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def dsld_label(label_id):
    r = requests.get(f"{BASE}/label/{label_id}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def upsert_product(conn, label):
    cur = conn.cursor()
    dsld_id = int(label.get("id"))
    cur.execute("""
        INSERT INTO products (dsld_label_id, full_name, brand_name, upc_sku, entry_date, off_market)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
          full_name=VALUES(full_name),
          brand_name=VALUES(brand_name),
          upc_sku=VALUES(upc_sku),
          entry_date=VALUES(entry_date),
          off_market=VALUES(off_market)
    """, (
        dsld_id,
        label.get("fullName"),
        label.get("brandName"),
        label.get("upcSku"),
        label.get("entryDate"),
        label.get("offMarket"),
    ))
    cur.execute("""
        INSERT INTO products_raw (dsld_label_id, raw_json)
        VALUES (%s, %s)
        ON DUPLICATE KEY UPDATE raw_json=VALUES(raw_json)
    """, (dsld_id, json.dumps(label)))
    conn.commit()

    cur.execute("SELECT id FROM products WHERE dsld_label_id=%s", (dsld_id,))
    product_id = cur.fetchone()[0]
    cur.close()
    return product_id

def normalize_name(name: str) -> str:
    return " ".join(name.strip().split()).lower()

def get_or_create_ingredient(conn, name):
    cur = conn.cursor()
    norm = normalize_name(name)
    cur.execute("SELECT id FROM ingredients WHERE name=%s", (norm,))
    row = cur.fetchone()
    if row:
        cur.close()
        return row[0]
    cur.execute("INSERT INTO ingredients (name) VALUES (%s)", (norm,))
    conn.commit()
    ing_id = cur.lastrowid
    cur.close()
    return ing_id

def extract_ingredients(label_json):
    """
    DSLD label JSON contains ingredient sections; exact field names can vary by label.
    Start by inspecting one label JSON and adjust parsing.
    """
    results = []

    # Common pattern: label_json may include supplementFacts with entries
    sf = label_json.get("supplementFacts") or []
    for panel in sf:
        # "supplementFactsEntries" is common in many label formats
        entries = panel.get("supplementFactsEntries") or []
        for e in entries:
            name = e.get("name") or e.get("ingredientName") or e.get("text")
            if not name:
                continue
            amt = e.get("amount")
            unit = e.get("unitName") or e.get("unit")
            raw_text = e.get("text") or None
            results.append((name, amt, unit, raw_text))

    return results

def main():
    conn = get_db()
    ensure_tables(conn)

    seen = set()
    for term in SEARCH_TERMS:
        start = 0
        page_size = 200

        while True:
            data = dsld_search(term, status=2, size=page_size, start=start)
            hits = (data.get("hits") or [])
            if not hits:
                break

            for hit in hits:
                # In search results, the DSLD label ID is typically in hit["_id"] :contentReference[oaicite:4]{index=4}
                label_id = int(hit.get("_id"))
                if label_id in seen:
                    continue
                seen.add(label_id)

                label = dsld_label(label_id)
                product_id = upsert_product(conn, label)

                # Parse and store ingredients
                for (name, amt, unit, raw_text) in extract_ingredients(label):
                    ing_id = get_or_create_ingredient(conn, name)
                    cur = conn.cursor()
                    cur.execute("""
                        INSERT INTO product_ingredients (product_id, ingredient_id, amount, unit, raw_text)
                        VALUES (%s, %s, %s, %s, %s)
                        ON DUPLICATE KEY UPDATE
                          amount=VALUES(amount),
                          unit=VALUES(unit),
                          raw_text=VALUES(raw_text)
                    """, (product_id, ing_id, amt, unit, raw_text))
                    conn.commit()
                    cur.close()

                time.sleep(0.2)  # be polite to the API

            start += page_size

    conn.close()
    print(f"Done. Loaded {len(seen)} unique labels.")

if __name__ == "__main__":
    main()
